#!/usr/bin/env bash

# Deploys ufw config for dev backend.

if [ $EUID -ne 0 ]; then
  echo 'Script must be run as root.'
  exit 1
fi

script_dir=$(dirname -- "$(readlink -f -- "$0")")

if [ ! -f $script_dir/../../server-ip-config ]; then
  echo 'server-ip-config does not exist.'
  exit 1
fi

source $script_dir/../../server-ip-config

ufw reset
ufw enable
ufw default deny incoming
ufw allow "OpenSSH"
ufw allow from $DEV_FE_IPV4 to any app "RabbitMQ"
ufw allow from $DEV_FE_IPV6 to any app "RabbitMQ"
ufw allow from $DEV_DMZ_IPV4 to any app "RabbitMQ"
ufw allow from $DEV_DMZ_IPV6 to any app "RabbitMQ"
ufw deny "RabbitMQ"
ufw allow "RabbitMQ Management"
ufw deny "RabbitMQ Cluster"
ufw deny "MySQL"
ufw deny "MySQL Replication"
ufw deny "Frontend"
