#!/usr/bin/env bash

# Deploys frontend files.

if [ $EUID -ne 0 ]; then
  echo 'Script must be run as root.'
  exit 1
fi

script_dir=$(dirname -- "$(readlink -f -- "$0")")
deploy_dir=/srv/jand-frontend

if [ ! -f $script_dir/src/includes/rabbitmq.ini ]; then
  echo 'rabbitmq.ini does not exist.'
  exit 1
fi

if [ ! -f $script_dir/jand-frontend.conf ]; then
  echo 'jand-frontend.conf does not exist.'
  exit 1
fi

echo "Copying frontend files."
if [ -d "$deploy_dir" ]; then
  rm -rf $deploy_dir/{..?*,.[!.]*,*}
else
  mkdir $deploy_dir
fi
cp -RTL $script_dir/src $deploy_dir
chown -R root:root $deploy_dir
chmod -R u=rwX,go=rX $deploy_dir
restorecon $deploy_dir &> /dev/null || :


echo "Copying Apache config file."
cp $script_dir/jand-frontend.conf /etc/apache2/sites-available/.
chown root:root /etc/apache2/sites-available/jand-frontend.conf
chmod -R u=rwX,go=rX /etc/apache2/sites-available/jand-frontend.conf
restorecon /etc/apache2/sites-available/jand-frontend.conf &> /dev/null || :

echo "Enabling Apache site file."
a2ensite jand-frontend

echo "Reloading Apache."
systemctl reload apache2.service
