#!/usr/bin/env bash

# Deploys ufw config for prod DMZ A.

if [ $EUID -ne 0 ]; then
  echo 'Script must be run as root.'
  exit 1
fi

script_dir=$(dirname -- "$(readlink -f -- "$0")")

if [ ! -f $script_dir/../../../server-ip-config ]; then
  echo 'server-ip-config does not exist.'
  exit 1
fi

source $script_dir/../../../server-ip-config

cp $script_dir/../../jand-ufw-profiles /etc/ufw/applications.d/jand-ufw-profiles
chown root:root /etc/ufw/applications.d/jand-ufw-profiles
chmod 0644 /etc/ufw/applications.d/jand-ufw-profiles
restorecon /etc/ufw/applications.d/jand-ufw-profiles &> /dev/null || :

ufw reset
ufw enable
ufw default deny incoming
ufw allow "OpenSSH"
ufw deny "RabbitMQ"
ufw deny "RabbitMQ Management"
ufw deny "RabbitMQ Cluster"
ufw deny "MySQL"
ufw deny "MySQL Replication"
ufw deny "Frontend"
ufw allow from $PROD_FE_B_IPV4 to any proto vrrp
ufw allow from $PROD_FE_B_IPV6 to any proto vrrp
