#!/usr/bin/env bash

# Deploys keepalived override.

if [ $EUID -ne 0 ]; then
  echo 'Script must be run as root.'
  exit 1
fi

script_dir=$(dirname -- "$(readlink -f -- "$0")")
deploy_dir=/etc/systemd/system/keepalived.service.d

if [ -d "$deploy_dir" ]; then
  rm -rf $deploy_dir/{..?*,.[!.]*,*}
else
  mkdir -p $deploy_dir
fi

cp $script_dir/keepalived-override.conf $deploy_dir/override.conf
chown root:root $deploy_dir/override.conf
restorecon $deploy_dir/override.conf &> /dev/null || :

systemctl daemon-reload

echo "Deployed override."