#!/usr/bin/env bash

# Deploys database connector files.

if [ $EUID -ne 0 ]; then
  echo 'Script must be run as root.'
  exit 1
fi

script_dir=$(dirname -- "$(readlink -f -- "$0")")
deploy_dir=/opt/jand-db-connector

if [ ! -f $script_dir/rabbitmq.ini ]; then
  echo 'rabbitmq.ini does not exist.'
  exit 1
fi

echo "Copying connector files."
rm -rf $deploy_dir/{..?*,.[!.]*,*}
cp -RTL $script_dir/src $deploy_dir
cp $script_dir/rabbitmq.ini $deploy_dir/.

echo "Copying systemd service file."
cp $script_dir/jand-db-connector.service /etc/systemd/system/.

echo "Reloading systemd daemon."
systemctl daemon-reload

echo "Enabling service."
systemctl enable jand-db-connector.service

echo "Starting service."
systemctl restart jand-db-connector.service
