#!/usr/bin/env bash

# Deploys ufw config for prod backend B.

if [ $EUID -ne 0 ]; then
  echo 'Script must be run as root.'
  exit 1
fi

script_dir=$(dirname -- "$(readlink -f -- "$0")")

if [ ! -f $script_dir/../../../server-ip-config ]; then
  echo 'server-ip-config does not exist.'
  exit 1
fi

source $script_dir/../../../server-ip-config

cp $script_dir/../../jand-ufw-profiles /etc/ufw/applications.d/jand-ufw-profiles
chown root:root /etc/ufw/applications.d/jand-ufw-profiles
chmod 0644 /etc/ufw/applications.d/jand-ufw-profiles
restorecon /etc/ufw/applications.d/jand-ufw-profiles &> /dev/null || :

ufw reset
ufw enable
ufw default deny incoming
ufw allow "OpenSSH"
ufw allow from $PROD_FE_A_IPV4 to any app "RabbitMQ"
ufw allow from $PROD_FE_A_IPV6 to any app "RabbitMQ"
ufw allow from $PROD_FE_B_IPV4 to any app "RabbitMQ"
ufw allow from $PROD_FE_B_IPV6 to any app "RabbitMQ"
ufw allow from $PROD_DMZ_A_IPV4 to any app "RabbitMQ"
ufw allow from $PROD_DMZ_A_IPV6 to any app "RabbitMQ"
ufw allow from $PROD_DMZ_B_IPV4 to any app "RabbitMQ"
ufw allow from $PROD_DMZ_B_IPV6 to any app "RabbitMQ"
ufw deny "RabbitMQ"
ufw allow "RabbitMQ Management"
ufw allow from $PROD_BE_A_IPV4 to any app "RabbitMQ Cluster"
ufw allow from $PROD_BE_A_IPV6 to any app "RabbitMQ Cluster"
ufw deny "RabbitMQ Cluster"
ufw allow from $PROD_BE_A_IPV4 to any app "MySQL"
ufw allow from $PROD_BE_A_IPV6 to any app "MySQL"
ufw deny "MySQL"
ufw allow from $PROD_BE_A_IPV4 to any app "MySQL Replication"
ufw allow from $PROD_BE_A_IPV6 to any app "MySQL Replication"
ufw deny "MySQL Replication"
ufw deny "Frontend
ufw allow from $PROD_BE_A_IPV4 to any proto vrrp
ufw allow from $PROD_BE_A_IPV6 to any proto vrrp
